# Do not keep production secrets in the repository,
# instead read values from the environment.
development:
  secret_key_base: 0e3bc1f396d483d8a640f73c30d4bdc342b5600b464d94cd9c750d085fdfe8b6bc7acd8f23259fa88c39c4b782d3e9b6a24aea18567a3916993f890ff476e4d4
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>

test:
  secret_key_base: 72406e2c3e688be0b98c561db8a9a471d34766aec6ab767e88136f6d5bbccad1c55380f08f248c048d4dac5b3622fb58e69ca212bc781e2d46f408b9ce357c34
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>
  
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>
